version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres-osm:test
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geopass
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata-test:
